name: OpenMRS frontend image build and push to Docker Hub

on:
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_MADIRO }}
          password: ${{ secrets.DOCKERHUB_TOKEN_MADIRO }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .  # This sets the context to the root of your repository
          file: frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME_MADIRO }}/openmrs3-backend:${{ env.BRANCH_NAME }}
          cache-from: type=gha 
          cache-to: type=gha,mode=max
